### ISSUE TITLE
@RequestParam expansion does not work when parameter name starts with $ - regression

### ISSUE THREAD

**Issue by ojecborec** [spring-cloud/spring-cloud-openfeign#109]
After upgrading to 2.1.0.RELEASE some of my clients stopped working properly. There is the same problem with the 2.1.0.RC3 version. Suppose I have a client

public interface Client {
    @GetMapping("/api")
    Result api(@RequestParam("$filter") String filter);
}

Calling client.api("123") used to work in any 2.0.x release even 2.1.0.RC2 was fine. Java call was translated into

GET /api?%24filter=123 HTTP/1.1

After upgrading to 2.1.0.RELEASE or 2.1.0.RC3 it looks like this

GET /api?%24filter=%7B%24filter%7D HTTP/1.1

**Comment by OlgaMaciaszek** [comment]
Hello @ojecborec I was able to replicate this issue, however, after verifying it I have noticed that the issue is caused by changes in the underlying OpenFeign (https://github.com/OpenFeign/feign) Feign-Core implementation, which has, indeed, been upgraded to 10.x in this project. 

The `{$filter}` query param is passed correctly to Feign, but there as it's being converted into a `feign.template.Expressions` type `feign.template.TemplateChunk`, it does not pass the following pattern matching filter:

```java
static {
    expressions = new LinkedHashMap<>();
    expressions.put(Pattern.compile("\\+(\\w[-\\w.]*[ ]*)(:(.+))?"), ReservedExpression.class);
    expressions.put(Pattern.compile("(\\w[-\\w.]*[ ]*)(:(.+))?"), SimpleExpression.class);
  }
```

```java
Optional<Entry<Pattern, Class<? extends Expression>>> matchedExpressionEntry =
        expressions.entrySet()
            .stream()
            .filter(entry -> entry.getKey().matcher(expression).matches())
            .findFirst();
```
You could create an issue with the OpenFeign team, however, the usage of `$` signs in queryParameter names seems rather peculiar and I'm not sure if OpenFeign team is going to work on that. If possible, I recommend removing the `$` signs from the query params in the client and upgrading the underlying API. a
