### ISSUE TITLE
The java.util.Set does not work as @RequestParam in Greenwich.SR1

### ISSUE THREAD

**Issue by Ziemowit** [spring-cloud/spring-cloud-openfeign#143]
After upgrade:
- from **spring-boot 2.0.8.RELEASE** / **spring-cloud Finchley.SR3**
- to **spring-boot 2.1.3.RELEASE** / **spring-cloud Greenwich.SR1**

our **@FeignClient** has an issue with passing **java.util.Set** as **@RequestParam** 

```
@RequestMapping("foo/{applicationId}/tools")
@FeignClient(name = "service-foo")
public interface ProxyShareTool {

  @GetMapping("/findDefaultIfVisibleByIds")
  Map<Long, TranslatedShareToolDTO> findVisible(@PathVariable("applicationId") String appId,
                                                @RequestParam("waveIds[]") Set<Long> waveIds,
                                                @RequestParam("lang") String lang);
}

```

After decode generated request we see following:

> findDefaultIfVisibleByIds?waveIds[]={waveIds[]}&lang=en

So seems that instead of ids following text was inserted 

> {waveIds[]}

**Comment by mm23504570** [comment]
I have same problem in Greenwich.RELEASE. I use `@RequestParam("ids[]") List<Integer> ids` as params. 
result is: 
``` 
{"timestamp":"2019-03-18T14:30:35.821+0000","status":400,"error":"Bad Request","message":"Failed to convert value of type 'java.lang.String' to required type 'java.util.List'; nested exception is java.lang.NumberFormatException: For input string: \"{ids[]}\"","path":"/"}
```
I found it caused by not matched Expression in Expressions.
Shall we put the `(Pattern.compile("(\\w[-\\w.]*[ ]*[\\[]*[\\]]*)(:(.+))?"), Expressions.SimpleExpression.class)` or create a new Expression in the expressions?

**Comment by OlgaMaciaszek** [comment]
Hello, @Ziemowit @mm23504570 Thanks for reporting this. I have triaged it and it appears to be an actual bug, however, its root cause can be found in the OpenFeign library. I have created this [issue](https://github.com/OpenFeign/feign/issues/928) and will be back here with any updates as soon as possible.

**Comment by Ziemowit** [comment]
Hooray!!! :)
