### ISSUE TITLE
spring-cloud-starter-openfeign  Why not include ribbon-loadbalancer jar ?

### ISSUE THREAD

**Issue by SoberChina** [spring-cloud/spring-cloud-openfeign#207]
Question
 The load in `spring-cloud-starter-openfeign ` uses ribbon. Why is there no ribbon package when encapsulating the jar?

Bug report
`spring-cloud-starter-openfeign` is starter ,Automatically creating beans should be supported. [FeignRibbonClientAutoConfiguration.java](https://github.com/spring-cloud/spring-cloud-openfeign/blob/35b9de7f6ef1669012cee5337a3943e7c16cc55a/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/FeignRibbonClientAutoConfiguration.java#L43)

**Comment by TYsewyn** [comment]
Which version are you using? Ribbon integration is an optional feature, so if you have Ribbon on the classpath it will be loaded.

**Comment by SoberChina** [comment]
That's not the question I'm asking.
I mean, since it's automatic configuration, why rely on other jars manually?
`spring-cloud-starter-openfeign` is starter ,Automatically creating beans should be supported.

**Comment by TYsewyn** [comment]
That's because `spring-cloud-openfeign` supports more than only Ribbon. We can't include all different possible implementations because that would cause interference on the classpath.
Therefor you need to pick the implementation you want and add that dependency to your project.
In case you didn't know, a lot of Spring Cloud Netflix projects have [entered maintenance mode](https://spring.io/blog/2019/01/23/spring-cloud-greenwich-release-is-now-available#spring-cloud-netflix-projects-entering-maintenance-mode) since the beginning of this year, amongst them is Ribbon.
We can't and won't change this in the future because of aforementioned reasons.

**Comment by SoberChina** [comment]
thanks
