### ISSUE TITLE
Enable OpenFeign's micrometer integration

### ISSUE THREAD

**Issue by vkochnev** [spring-cloud/spring-cloud-openfeign#354]
We want our OpenFeign clients to report metrics, but there are several points that prevent us from doing it clear.
- `spring-cloud-openfeign-dependencies` manages specific OpenFeign modules instead of importing `feign-bom` so we have to redeclare OpenFeign version property to add `feign-micrometer` dependency, which is error prone.
- OpenFeign has a notion of `Capability` which is aimed on customization of client parts, but `spring-cloud-openfeign` doesn't use it at the moment and `feign-micrometer` module (available since version 10.9) exposes `MicrometerCapability` to provide metrics. It'd be much better if Spring Cloud will provide a generic capability registrar so others won't need to implement it by themselves.
- As it was mentioned earlier OpenFeign provides the `MicrometerCapability` implementing metering, if there will be infrastructure it can be enabled in a very straightforward way, but it also can be enabled by default or with some switch.

**Comment by spencergibb** [comment]
Please open a separate issue for the bom

**Comment by okue** [comment]
When will the feature be supported?

**Comment by timpeeters** [comment]
@spencergibb pull request created for the bom.
https://github.com/spring-cloud/spring-cloud-openfeign/pull/461

Would you mind having a look? Thanks!

**Comment by shakuzen** [comment]
I think this was resolved by #462 /cc @jonatan-ivanov

**Comment by jonatan-ivanov** [comment]
Yepp, #462 should resolve this, see:
- [Capability support](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#feign-capability-support)
- [Micrometer support](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#feign-metrics)

You only need to put `feign-micrometer` on the classpath.

I'm closing this issue because of the above, please let me know if we misunderstood it and you want us to reopen.
