### ISSUE TITLE
Changes in the latest version

### ISSUE THREAD

**Issue by xhyym** [spring-cloud/spring-cloud-openfeign#846]
Hello, when I recently looked at the latest code of this project, I did not find the integration of ribbon, but found many new loadbalancerClass, is it to move the ribbon out of Feign's plan, are these new loadbalancerClass any new benefits compared to ribbon, I hope to receive your reply, thank you.
![image](https://user-images.githubusercontent.com/59786372/224269530-ff8104c1-cde9-4847-8cdf-48fa0d1376c8.png)

**Comment by OlgaMaciaszek** [comment]
Hello @xhyym, that happened a few years back. Spring Cloud Netflix Ribbon and any Ribbon integrations have not been supported since `3.0.x` and the currently supported versions of Spring Cloud OpenFeign are `3.1.6` and `4.0.1` (release trains `2021.0.x` and `2022.0.x`. Spring Cloud LoadBalancer is the suggested replacement for Ribbon in any Spring Boot and Spring Cloud-based projects and is also now being used in Spring Cloud OpenFeign. You can find all the information [in the docs](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/).
