### ISSUE TITLE
Upgrade to Feign 10.1.0

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-openfeign#85]
There's Feign 9.7.0 in [dependencies](https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-dependencies/pom.xml#L10)

Should  be upgraded to 10.1.0.

**Comment by OlgaMaciaszek** [comment]
There are issues that would make it not backward compatible, so we would have to wait with that for a major release. Below is a summary:

It looks like Feign has switched to only handling text bodies - UTF-8 charset is set by default, the `body()` method does not change the request charset anymore and there is no accessible setter to do it manually and we have methods in `SpringEncoder` that also handled binary and protobuf bodies; I'm still planning to discuss it with the OpenFeign devs, but most probably we would have to remove support for those files as well.

The functionality related to operating on uris has been changed. The method `feign.RequestTemplate#insert` that we use in `org.springframework.cloud.openfeign.support.SpringMvcContract#processAnnotationOnClass` is now deprecated and it also does a different thing that what it did before - it now sets absolute host name and not the remaining path segments -as previously-; I guess we could be able to executed the same operations on the uris using the new `uriTemplate` field, however it has private read access as of now - it has a public write access and append possibility, but since we used the previous `insert()` implementation to prepend the uris with segments from `@RequestMapping` annotations, it would not be sufficient for us - I guess public read access would have to be added for `uriTemplate` to maintain same functionality on our side. Alternatively, we could try to use `path()` to extract the segments present in `uriTemplate()` and then prepend them with segments from the annotations and set in `requestTemplate` using `uri()` method, but that would be hacky and I don't really like the idea.

The `feign.Contract.BaseContract#parseAndValidateMetadata` method has started adding query parameters when we have a `@RequestParam` `List` method parameters - we could fix it, though, by not calling the original method in our implementation and, instead, implementing that bit ourselves.

**Comment by robachmann** [comment]
Thank so you much for your preliminary work, @OlgaMaciaszek. I really hope you manage to upgrade the dependency to a newer version in the near future. Maybe there will be a Feign version `10.2.0` or `11.0.0` where Spring and Feign meet in the middle with some shared concepts.
As a developer I hope being able to access `FeignException`'s content in a future version. 
Keep it up and thank you again

**Comment by kdavisk6** [comment]
@OlgaMaciaszek 

Feel free to raise this issues on the OpenFeign repository.  I'm mostly responsible for these changes as much of `RequestTemplate`'s functionality expressed intent vs. their usage was at odds.  For instance, `insert` had different semantics depending on where it was called during `Contract` validation.  For example, when using the `JAXRSContract` `insert` was replacing the entire uri set, whereas in the default `Contract` it was being used to prepend the host and scheme.

To make this intent clearer, `target` was added.  Looking over the code here:

https://github.com/spring-cloud/spring-cloud-openfeign/blob/cc2fe823c3001a79ecba9f58b5393cb2ea30b28a/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java#L125-L134

moving to `target` will have the same result as using `insert()`, setting the initial url from the `RequestMapping` annotation.  Take the following example:

```java
@FeignClient
@RequestMapping('https://api.github.com')
public interface GitHub {
   @RequestMapping('/api/repos/{stuff}')
   public void getStuff(@RequestParam('stuff') String moreStuff)
}
```
Replacing `insert(0, pathValue)` with `target(pathValue)` will result in all requests for this interface to start with `https://api.github.com`.  This is what I understand your intent is, but please let me know if I am missing something.

On the issue with `body` and the charset, you can use `Request.Body.encoded(byte[], charset)` instead of the previous `body(byte[] data, Charset charset)`.  This was added because we ran into a number of issues regarding consistent results when encoding text based bodies.  You should be able to send binary data and omit the charset and it should still work.

As with all of these suggestions, if they don't work out, please feel free to reach out to me and I'll do what I can to help.

**Comment by kdavisk6** [comment]
My apologies, I made a mistake in my earlier comment. When processing the RequestMapping annotation on a class, please use the uri methods and not target. 

There are two versions of uri, one with the append Boolean and one without. To start building the uri, use the simple signature. Then, when processing the method annotations, use the extended signature setting append to true. 

This is the same method we use in our JAXRS contract.

**Comment by OlgaMaciaszek** [comment]
@kdavisk6 Thanks, will check it out and get back to you - yes, indeed, I've tried using `target` which has been used instead of `insert` and it required absolute uris. Will verify with `uri()` instead.

**Comment by OlgaMaciaszek** [comment]
@kdavisk6 These changes have helped - thanks a lot :) . I still need to verify more cases for processing annotations and, if necessary change the implementation for Spring contracts - we might be able to upgrade it after all :).

**Comment by kdavisk6** [comment]
@OlgaMaciaszek 

Great news.  Please do not hesitate to reach out if you run into any additional issues or have more questions.

**Comment by OlgaMaciaszek** [comment]
@kdavisk6 Thanks again for your suggestions - they were helpful and it seems that the upgrade will work. I've filed this PR. If you have any review suggestions, feel free to jump in and comment: https://github.com/spring-cloud/spring-cloud-openfeign/pull/95
