### ISSUE TITLE
Why pathvariable annotation must have value?

### ISSUE THREAD

**Issue by MikeSya** [spring-cloud/spring-cloud-openfeign#891]
In the `PathVariableParameterProcessor` (spring-cloud-openfeign-core-2.1.0), we can see the method of `processArgument`, which is used to process `@PathVariable` annotation's value, if value is `null` that will produce error message. But the method has the paramter of method, why  we can not  get the parameter belongs to the method, and try to get its parameter name to fill the path

**Comment by OlgaMaciaszek** [comment]
Hello, @MikeSya. Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). Also, please upgrade to a supported Spring Cloud OpenFeign version (`4.0.4` or `4.1.1`) since `2.1.0` has been out of support for a long time. 
If you try it in your app, you will be able to see that it works already. This is because it's handled under the hood by [this method](https://github.com/spring-cloud/spring-cloud-openfeign/blob/f2cc8923213fde8f348361b8311c0e9af447235d/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java#L381C32-L393).
